
### GET ALL
GET http://json-server-theta.herokuapp.com/carts


### DELETE BY ID
DELETE https://json-server-theta.herokuapp.com/carts/7
Content-Type: application/json

### DELETE ALL
DELETE https://json-server-theta.herokuapp.com/carts?userId=XBTFAIN25md33dbqMgksekcWyKC3
Content-Type: application/json