### GET ALL from Heroku
GET https://json-server-theta.herokuapp.com/products

### GET ALL
GET https://json-server-theta.herokuapp.com/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

### GET BY Id
GET https://json-server-theta.herokuapp.com/products/11
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

### GET BY Parameters
GET https://json-server-theta.herokuapp.com/products?first_name=S&id=1&id=2
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

### GET BY Colors
GET https://json-server-theta.herokuapp.com/products?colors_like=violet&colors_like=Crimson

### GET BY Global Search
GET https://json-server-theta.herokuapp.com/products?q=Violet

### GET BY Pagination
GET https://json-server-theta.herokuapp.com/products?_page=3&_limit=2

### CREATE
POST https://json-server-theta.herokuapp.com/products
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

  {
    "id": 11,
    "title": "The Pop Shoppe Pinapple",
    "desc": "posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",
    "small_desc": "ultrices enim lorem ipsum",
    "gender": "Male",
    "ratings": 2,
    "colors": [
      "Violet",
      "Violet",
      "Mauv"
    ],
    "brand": "abc",
    "price": 88,
    "price_without_discount": 97.2,
    "seller": "pedeafera"
  }

### UPDATE BY ID
PUT https://json-server-theta.herokuapp.com/products/11
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

  {
    "title": "The Title",
    "desc": "posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl",
    "small_desc": "ultrices enim lorem ipsum",
    "gender": "Male",
    "ratings": 2,
    "colors": [
      "Violet",
      "Violet"
    ],
    "brand": "abc",
    "price": 88,
    "price_without_discount": 97.2,
    "seller": "pedeafera"
  }

### DELETE BY ID
DELETE https://json-server-theta.herokuapp.com/products/11
Content-Type: application/json

### DELETE BY ID
DELETE https://json-server-theta.herokuapp.com/products/11
Content-Type: application/json