
### GET ALL
GET http://localhost:3000/reviews?product_id=2


### CREATE
POST http://localhost:3000/reviews
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjksImlhdCI6MTU5NDE4NDc5N30.JXdUTFhrDUv6MnqP4_iGwvfm2SctTsPs2N9jw_Hg-l8

{
    "id": 6,
    "product_id": 2,
    "ratings": 3,
    "review": "posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nis"
}
